# Generated by Django 4.1.2 on 2022-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor/Hora')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.URLField(max_length=255)),
            ],
        ),
    ]
