# Generated by Django 4.1.2 on 2022-10-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_professor', to='teacher.professor', verbose_name='Professor')),
            ],
        ),
    ]
